version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: federated-msp-umbrel-app_web_1
      APP_PORT: 3000

  web:
    image: ericpp/federated-msp@sha256:4735cd00c9d7dff8ba588acb439f1b850cd26f975241e19d916d112609228a3b
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/mspDB:/usr/src/app/msp/mspDB
      - ${APP_DATA_DIR}/data/public:/usr/src/app/msp/public
    environment:
      ADMIN_USER: admin
      ADMIN_PASS: "${APP_PASSWORD}"
